### ISSUE TITLE
opening project doesn't find config

### ISSUE THREAD

**Issue by Goddard** [KenN7/vim-arsync#9] opened 2021-01-13 13:29 UTC
Error : "Could not locate .vim-arsync file aborting"

but ARShowConf works perfectly fine.

It is strange because it knows to try to upload on write, but not where the conf is?  Do I have to have a conf file in ever single sub folder?

If I open with
nvim
nvim .
nvim projectFolder/ 

Nothing seems to have an effect.  Any ideas?

Thanks

**Comment by KenN7** [comment] 2021-01-13 14:17
Hi,
Unfortunately, I cannot reproduce your error :/

The `.vim-arsync` needs to be at the root of your project.

For example with the following structure, i'm always able to upload (`:ARsyncUp`). No matter if i open the folder with vim/nvim and from `nvim .`, `nvim projectFolder`, directly `nvim main.txt`, or even `nvim tt.txt`
```
.
├── main.txt
├── test
│   ├── tt
│   │   └── rtrt
│   └── tt.txt
└── .vim-arsync
```

The .vim-arsync file contains:
```
remote_host     example.com 
remote_user     user
#remote_passwd  secret 
local_path      /home/user/temp
remote_path     /home/remote/temp
ignore_dotfiles 1
auto_sync_up    0
```

**Comment by Goddard** [comment] 2021-01-13 14:28
I am running this on Windows inside WSL2 Ubuntu if that makes a difference.   Not sure where you tested.

**Comment by KenN7** [comment] 2021-01-13 14:31
ow ok, that maybe it, i'm running linux and can't quite get my hand on a windows machine right now.
I'll check if i have some time in the coming week.
I think it could maybe be related to the way hidden files are handled in win/linux ? the name `.vim-arsync` with the `.` at the beginning it maybe not valid ?

**Comment by Goddard** [comment] 2021-01-13 16:46
I just tested on my other laptop running Kubuntu 19.10 and I get the same error.

What distro are you using?

**Comment by KenN7** [comment] 2021-01-13 17:01
tested on debian 10 and archlinux, also using vim-plug.
can you post the output on  `tree -a` in your project folder ?

**Comment by Goddard** [comment] 2021-01-19 16:10
I think it may have something to do with the actual format of the file.

After I updated it and changed the format it gives me a new error.

ssh: Could not resolve hostname goddard

But I have the hostname set as an IP address.  Is this config file read via a space or tab and then a new line is supposed to be a line break?

:ARshowConf looks right though.
{'ignore_dotfiles': '0', 'remote_passwd': 'my_password', 'remote_host': '192.168.11.19', 'local_path': '/mnt/c/Users/ryein/source/repos/project', 'remote_path': '/home/goddard/Documents/project/var/www/html', 'auto_sync_up': '1', 'remote_user': 'goddard'}

So I don't know what the issue is.

**Comment by KenN7** [comment] 2021-01-19 18:13
Hi, i discovered a bug when using plain text password, i just pushed a fixe in the dev branch, it requires that you install sshpass on your computer.

**Comment by KenN7** [comment] 2021-01-19 18:15
i close for now, let me know if it doesnt work.
Cheers

**Closed** 2021-01-19 18:14 UTC

**Comment by Goddard** [comment] 2021-01-19 21:17
works great.  Cheers!

**Comment by KenN7** [comment] 2021-07-05 09:45
Hi there, sorry for not answering earlier, i'm not sure i remember why i had put ".,,;" , 
I dont have much time myself to test it out, did you experiment a bit with the change ?

**Comment by hellmind** [comment] 2021-07-05 22:16
Now it works.
